Extract start_uim_tmux()

diff --git a/uim-tmux b/uim-tmux
--- a/uim-tmux
+++ b/uim-tmux
@@ -1,39 +1,56 @@
 #!/bin/bash
 
+set -o pipefail
+
+start_uim_tmux() {
+    sock=$1
+    shift
+    session=$1
+    shift
+
+    ls $(dirname $sock) 2> /dev/null 1>&2 || mkdir $(dirname $sock)
+
+    uim-fep-tick -s $sock | while read line; do
+      tmux set -t $session status-left "$(echo $line | sed -e 's/.*Sk\(.\).*/[\1]/')" 2> /dev/null 1>&2
+    done &
+
+    uim-fep -b $sock -s backtick -e tmux attach-session -t $session $@
+    kill `jobs -p`
+}
+
 new_session() {
     # launch tmux
     # get session id
     session=$(echo "display-message -p -F '#S'" | tmux $GLOBAL_OPT -C new-session $@ | grep -v '^%' | tail -n 1)
-    if [ -z "$session" ]; then
+    if [ -z "$session" -o $? -ne 0 ]; then
+        echo "unexpected error"
         exit 1
     fi
 
-    sock="/tmp/uim-tmux/$session.sock"
-    uim-fep-tick -s $sock | while read line; do
-      tmux set -t $session status-left "$(echo $line | sed -e 's/.*Sk\(.\).*/[\1]/')" 2> /dev/null 1>&2
-    done &
-
-    ls /tmp/uim-tmux 2> /dev/null 1>&2 || mkdir /tmp/uim-tmux
-    uim-fep -b $sock -s backtick -e tmux attach-session -t $session
-
-    # cmd_attach_session -> cmd_find_session -> cmd_choose_session_list
-    # https://github.com/ThomasAdam/tmux/blob/bd803e82e96512473036461ec3832c569768e535/cmd.c#L434-L437
+    start_uim_tmux "/tmp/uim-tmux/$session.sock" $session
 }
 
 attach_session() {
-    session=$(echo "display-message -p -F '#S'" | tmux -C attach-session $@ | grep -v '^%' | tail -n1)
-    if [ -z "$session" ]; then
+    # -t が空だった時、最近アクティブだったセッションが選ばれる。
+    # https://github.com/tmux/tmux/commit/3aa72b42b2a317b0ae531219d269f2a636d6482a
+    # の変更が入ってる場合なら対象のsession idを
+    # tmux list-sessions -F'#{session_activity} #{session_id} #{session_name}' |
+    #     tr -d '$' | sort -k 1 -k 2n | awk '{print $2}' | tail -n 1
+    # とかって取れるけど、そういうわけでもない環境でも使うのでコントロールモードで一回attachしてみてとってくる
+    #
+    # c.f. cmd_attach_session -> cmd_find_session -> cmd_choose_session_list
+    #      https://github.com/ThomasAdam/tmux/blob/bd803e82e96512473036461ec3832c569768e535/cmd.c#L434-L437
+
+    session=$(echo "display-message -p -F '#S'" | tmux $GLOBAL_OPT -C attach-session $@ | grep -v '^%' | tail -n 1)
+    if [ -z "$session" -o $? -ne 0 ]; then
+        echo "no sessions"
         exit 1
     fi
 
-    sock="/tmp/uim-tmux/$session.sock"
-    uim-fep-tick -s $sock | while read line; do
-      tmux set -t $session status-left "$(echo $line | sed -e 's/.*Sk\(.\).*/[\1]/')" 2> /dev/null 1>&2
-    done &
-
-    ls /tmp/uim-tmux 2> /dev/null 1>&2 || mkdir /tmp/uim-tmux
-    uim-fep -b $sock -s backtick -e tmux $GLOBAL_OPT attach-session $@
+    start_uim_tmux "/tmp/uim-tmux/$session.sock" $session $@
 }
+
+CONTROL_MODE=0
 
 # consume tmux's global opts
 # https://github.com/tmux/tmux/blob/7acc4addb51c711afed3761302c2d3457125445c/tmux.c#L223
@@ -59,5 +76,3 @@ case $1 in
         tmux $GLOBAL_OPT $@
         ;;
 esac
-
-kill `jobs -p`
